[build]
command = "npm run build && npx @cloudflare/next-on-pages"
cwd = "."

[site]
bucket = ".vercel/output/static"

[env.production]
name = "keyboard-tester"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_do_not_populate_process_env"]

[env.production.vars]
NODE_VERSION = "18.18.0"

[env.preview]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_do_not_populate_process_env"]

[env.preview.vars]
NODE_VERSION = "18.18.0" 